# Generated by Django 4.0.1 on 2022-01-27 08:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileupload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
                ('filepath', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='priyanshu',
        ),
    ]
