# Generated by Django 4.0.1 on 2022-01-29 10:51

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_fileupload_filepath_alter_fileupload_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='filepath',
            field=models.FileField(null=True, upload_to=apps.home.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='id',
            field=models.CharField(default=apps.home.models.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
